name: Segurança de Aplicativos
logo: 
short-description:
key-objectives:
  - A segurança do aplicativo descreve as medidas de segurança no nível do aplicativo que visam impedir que dados ou códigos dentro do aplicativo sejam roubados ou invadidos. Ele abrange as considerações de segurança que ocorrem durante o desenvolvimento e o design de aplicativos, mas também envolve sistemas e abordagens para proteger os aplicativos depois que eles são implantados. 
contents:
  - type: ARTICLE
    title: "Application security vs. software security"
    link: https://medium.com/@SW_Integrity/application-security-vs-software-security-whats-the-difference-3d345413927c
  - type: ARTICLE
    title: "A Comprehensive Guide To Application Security"
    link: https://medium.com/edureka/application-security-tutorial-e6a0dda25f5c
  - type: ARTICLE
    title: "Application Security Best Practices"
    link: https://medium.com/@cloud_tips/application-security-best-practices-c63b79f29a99
  - type: ARTICLE
    title: "Importance of Software Security"
    link: https://medium.com/nerd-for-tech/importance-of-software-security-application-security-non-technical-hacking-encryption-and-365c93def04e
  - type: YOUTUBE
    title: "Application Security "
    link: https://www.youtube.com/watch?v=gfFKuiZ9Y7s
  - type: YOUTUBE
    title: "Secure by Design"
    link: https://www.youtube.com/watch?v=4qN3JBGd1g8
  - type: YOUTUBE
    title: "Application Security 101"
    link: https://www.youtube.com/watch?v=wcpWSSorxuk
  - type: YOUTUBE
    title: "What you need to know in 8 minutes"
    link: https://www.youtube.com/watch?v=Dp019cWu1cg
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/
  - type: COURSE
    title: "DEVSECOPS SECURING CI/CD & DEVOPS"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/devsecops-securing-cicd-devops/