name: Segurança em autenticação e senhas
logo: 
short-description:
key-objectives:
  - Uma senha forte faz toda diferença quando o assunto é proteção de dados. Afinal, ela é construída de maneira a dificultar e muito que seja quebrada por um hacker ou ataque de massa. A senha, você sabe, é um mecanismo que permite o acesso de uma pessoa a um determinado serviço.
contents:
  - type: SITE
    title: "How Secure is Your Password?"
    link: https://www.passwordmonster.com/
  - type: ARTICLE
    title: "Como criar senhas realmente seguras"
    link: https://medium.com/the-autistic-nikkei/como-criar-senhas-realmente-seguras-d39b4442db1c
  - type: ARTICLE
    title: "Password Security: THM Writeup"
    link: https://medium.com/bug-bounty-hunting/password-security-thm-writeup-cc9088207af3
  - type: ARTICLE
    title: "What Is a Secure Password?"
    link: https://medium.com/geekculture/what-is-a-secure-password-97263aeedea9
  - type: YOUTUBE
    title: "Bit Oxygen: Authentication in Computer Security"
    link: https://www.youtube.com/watch?v=7oTkgG1v-rU
  - type: YOUTUBE
    title: "Linus Tech Tips: Password Security Best Practices"
    link: https://www.youtube.com/watch?v=t8SQo3R7qeU
alura-contents:
  - type: COURSE
    title: "Cyber Security Fundamentals & Skills"
    link: https://www.fiap.com.br/shift/curso/tecnologia/cyber-security-fundamentals-e-skills-online/
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/