name: Segurança em Cloud
logo: 
short-description:
key-objectives:
  - A segurança na nuvem, também conhecida como segurança da computação em nuvem, é um conjunto de medidas de segurança projetadas para proteger a infraestrutura, os aplicativos e os dados baseados em nuvem. Essas medidas garantem a autenticação de usuários e dispositivos, controle de acesso a dados e recursos e proteção de privacidade de dados . Eles também suportam a conformidade de dados regulatórios .
contents:
  - type: ARTICLE
    title: "Security in Cloud Computing"
    link: https://medium.com/cyversity/security-in-cloud-computing-8d77b20e7a2d
  - type: ARTICLE
    title: "What Is Cloud Security Posture Management?"
    link: https://blog.cloudboost.io/what-is-cloud-security-posture-management-7ca9650d18e6
  - type: ARTICLE
    title: "Cloud Applications Concept"
    link: https://medium.com/databulls/new-era-cloud-applications-concept-and-security-4ccfe29db9d7
  - type: ARTICLE
    title: "Security IN the Cloud vs Security OF the Cloud"
    link: https://medium.com/nerd-for-tech/security-in-the-cloud-vs-security-of-the-cloud-114dbcf962a9
  - type: YOUTUBE
    title: "What is Cloud Security?"
    link: https://www.youtube.com/watch?v=jI8IKpjiCSM
  - type: YOUTUBE
    title: "Introduction to Application Security"
    link: https://www.youtube.com/watch?v=3QOlo2pEpvc
  - type: YOUTUBE
    title: "Cloud Security Tutorial"
    link: https://www.youtube.com/watch?v=0lw4KU5wHsk
  - type: YOUTUBE
    title: "Cloud Security Fundamentals"
    link: https://www.youtube.com/watch?v=M_9hRPVH5SA
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/
  - type: COURSE
    title: "DEVSECOPS SECURING CI/CD & DEVOPS"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/devsecops-securing-cicd-devops/