name: Feedback e melhoria contínua
logo:
short-description:
key-objectives:
  - Implementar mecanismos eficazes para coletar feedback de clientes.
  - Analisar feedbacks para identificar padrões e oportunidades de melhoria.
  - Promover uma cultura de aprendizado contínuo com base nas avaliações dos clientes.
aditional-objectives:
contents:
alura-contents:
  - type: COURSE
    title: "Vendas de alta performance: entendendo a necessidade do cliente"
    link: https://cursos.alura.com.br/course/vendas-entendendo-a-necessidade-do-cliente
  - type: COURSE
    title: "Vendas de alta performance:técnicas para melhorar seu aprendizado"
    link: https://www.alura.com.br/curso-online-vendas-aprenda-a-aprender
  - type: COURSE
    title: "Mediação de conflitos: construa soluções efetivas"
    link: https://cursos.alura.com.br/course/mediacao-conflitos-solucoes-efetivas