name: Segurança Física
logo: 
short-description:
key-objectives:
  - A segurança física é a proteção de pessoas, propriedades e ativos físicos de ações e eventos que podem causar danos ou perdas. Embora muitas vezes negligenciada em favor da segurança cibernética, a segurança física é igualmente importante.
contents:
  - type: ARTICLE
    title: "What Is Physical Security"
    link: https://medium.com/the-sine-in/what-is-physical-security-understanding-workplace-safety-76a9b4e7df47
  - type: ARTICLE
    title: "Cyber Security and Physical Security"
    link: https://rchen8.medium.com/cyber-security-and-physical-security-are-very-different-22e31a933907
  - type: ARTICLE
    title: "What is a Physical Security Architect?"
    link: https://jay-pang.medium.com/what-is-a-physical-security-architect-2e8bd8b4b130
  - type: ARTICLE
    title: "Physical Security"
    link: https://medium.com/@rezaduty/physical-security-9c869bed76
  - type: YOUTUBE
    title: "Physical Security Part 1: Intro and Site Barriers"
    link: https://www.youtube.com/watch?v=j9MQMVn3FV4
  - type: YOUTUBE
    title: "Physical Security Part 2 - Walls, Doors, and Locks"
    link: https://www.youtube.com/watch?v=EAeVUDMDSn4
  - type: YOUTUBE
    title: "Physical Security Part 3 - Lights, Sensors, and Alarms"
    link: https://www.youtube.com/watch?v=tyFkj5UrPJQ
  - type: YOUTUBE
    title: "Physical Security Part 4 - Environmental Controls"
    link: https://www.youtube.com/watch?v=o_ENagQ60nY
  - type: COURSE
    title: "Cyber Security Fundamentals & Skills"
    link: https://www.fiap.com.br/shift/curso/tecnologia/cyber-security-fundamentals-e-skills-online/
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/