name: Product Discovery
logo:
short-description:
key-objectives:
  - Product Discovery é o processo de entender as necessidades dos usuários, identificar oportunidades de mercado e conceber soluções inovadoras para desenvolver produtos bem-sucedidos.
  - Analise o mercado para identificar tendências e oportunidades.
  - Conduza entrevistas para entender as necessidades dos usuários.
  - Crie protótipos para validar ideias e conceitos com os usuários.
  - Estude os concorrentes para identificar lacunas e diferenciais.
  - Teste hipóteses para validar a viabilidade do produto.
  - Mapeie as jornadas dos usuários para identificar pontos de dor.
aditional-objectives:
contents:
  - type: ARTICLE
    title: "Product Discovery: o que é, como fazer e como funciona?"
    link: https://rockcontent.com/br/talent-blog/product-discovery/
  - type: ARTICLE
    title: "O que é Product Discovery, como se diferencia do Product Delivery, e qual o seu valor na Estratégia de crescimento da Empresa"
    link: https://medium.com/@pravy.design/o-que-é-product-discovery-como-se-diferencia-do-product-delivery-e-qual-o-seu-valor-na-estratégia-9cdae6c50e2c
  - type: ARTICLE
    title: "Product Discovery: o que é, como fazer e quais as melhores técnicas"
    link: https://produtosincriveis.co/blog/product-discovery-o-que-e-como-fazer-e-quais-as-melhores-tecnicas
alura-contents:
  - type: PODCAST
    title: "Product Discovery - Hipsters #188"
    link: https://cursos.alura.com.br/extra/hipsterstech/product-discovery-hipsters-188-a372
  - type: PODCAST
    title: "Product Discovery - Layers ponto tech #114"
    link: https://cursos.alura.com.br/extra/layerstech/product-discovery-layers-ponto-tech-114-a1958
  - type: COURSE
    title: "Gestão de produtos digitais: Product Discovery"
    link: https://cursos.alura.com.br/course/gestao-produtos-digitais-product-discovery
  - type: COURSE
    title: "Startupismo: Product Discovery"
    link: https://cursos.alura.com.br/course/startupismo-product-discovery