name: Product Manager
logo:
short-description:
key-objectives:
  - Product Manager é quem busca gerenciar o processo de Product Discovery garantindo que as necessidades dos usuários sejam compreendidas e que as soluções sejam alinhadas com as oportunidades de mercado.
  - Supervisionar a análise de mercado para identificar tendências e oportunidades estratégicas que posicionem o produto de forma competitiva.
  - Coordenar a criação e validação de protótipos para assegurar que as ideias e conceitos sejam sólidos e que atendam às expectativas do mercado.
contents:
  - type: ARTICLE
    title: "Product Manager: o que faz, salário e como ingressar na profissão"
    link: https://www.cursospm3.com.br/blog/product-manager-guia-o-que-faz-salario-como-ingressar-na-profissao/#:~:text=O%20cargo%20de%20Product%20Manager,ativamente%20o%20sucesso%20da%20empresa.
  - type: YOUTUBE
    title: "Como é ser Product Manager no Nubank"
    link: https://www.youtube.com/watch?v=cy1YwS57wa8
alura-contents:
  - type: COURSE
    title: "Product Manager: uma jornada em gestão de produto"
    link: https://cursos.alura.com.br/course/product-manager-jornada-gestao-produto
  - type: ARTICLE
    title: "Product Manager: O que é e como se destacar na área"
    link: https://www.alura.com.br/artigos/product-manager-o-que-e-e-como-se-destacar
