name: Priorização
logo:
short-description:
key-objectives:
  - Identificar e aplicar métodos eficazes de priorização, como "Kano Model" e "Moscow", para garantir que os recursos mais valiosos sejam desenvolvidos primeiro.
  - Analisar a relação entre risco e valor para tomar decisões informadas que equilibrem a inovação com a viabilidade técnica e comercial.
  - Utilizar o User Story Map para organizar e priorizar o backlog de forma visual, facilitando a quebra de atividades maiores em tarefas menores e mais gerenciáveis.
  - Avaliar o impacto do Cost of Delay para determinar a urgência das funcionalidades e otimizar o tempo de lançamento do produto no mercado.
contents:
  - type: ARTICLE
    title: "Glossário - Kano Model"
    link: https://www.cursospm3.com.br/glossario/kano-model/
  - type: ARTICLE
    title: "Método MoSCoW: framework para ajudar a priorizar tarefas"
    link: https://www.cursospm3.com.br/blog/metodo-moscow-framework-para-priorizar-tarefas
  - type: ARTICLE
    title: "O que é User Story Mapping?"
    link: https://www.cursospm3.com.br/blog/o-que-e-user-story-mapping/
  - type: ARTICLE
    title: "O que é o Custo de Atraso e Como Otimizar seu Processo"
    link: https://businessmap.io/pt/gestao-lean/valor-desperdicio/custo-de-atraso
alura-contents:
  - type: COURSE
    title: "Gestão de produtos digitais: priorização"
    link: https://cursos.alura.com.br/course/gestao-produtos-priorizacao