name: Fundamentos de product managment
logo:
short-description:
key-objectives:
  - Product Management é o processo de desenvolver, lançar e gerenciar produtos de forma eficaz para atender às necessidades dos clientes e alcançar objetivos de negócios.
  - Defina uma visão clara e estratégia para o produto.
  - Entenda as necessidades e preferências dos clientes.
  - Especifique os requisitos e funcionalidades do produto.
  - Priorize recursos com base no valor para o cliente e para o negócio.
  - Colabore com equipes de desenvolvimento para entregar incrementos de valor.
  - Gerencie o ciclo de vida do produto e faça ajustes conforme necessário.
  - Analise métricas e feedback para orientar decisões.
  - Comunique-se claramente com todas as partes interessadas.
  - Esteja aberto a mudanças e ajuste a estratégia conforme necessário.
aditional-objectives:
contents:
  - type: ARTICLE
    title: "Fundamentos de Product Management"
    link: https://www.cursospm3.com.br/blog/fundamentos-product-management/
  - type: ARTICLE
    title: "Product Manager: o que faz, salário e como ingressar na profissão"
    link: https://www.cursospm3.com.br/blog/product-manager-guia-o-que-faz-salario-como-ingressar-na-profissao/
  - type: ARTICLE
    title: "Entenda o que faz um Product Manager e qual a sua importância para o sucesso do seu produto"
    link: https://rockcontent.com/br/blog/product-manager/
  - type: SITE
    title: "MBA em PRODUCT MANAGEMENT & GROWTH HACKING - FIAP"
    link: https://www.fiap.com.br/mba/mba-em-product-management-growth-hacking-discovery-delivery-scale
alura-contents:
  - type: ARTICLE
    title: "Product Manager: O que é e como se destacar na área"
    link: https://www.alura.com.br/artigos/product-manager-o-que-e-e-como-se-destacar
  - type: COURSE
    title: "Product Management: agilize o desenvolvimento de produtos"
    link: https://cursos.alura.com.br/course/product-management-desenvolvimento-produtos
  - type: COURSE
    title: "Product Manager: uma jornada em gestão de produto"
    link: https://cursos.alura.com.br/course/product-manager-jornada-gestao-produto