name: Product Design
logo:
short-description:
key-objectives:
  - O primeiro passo para explorarmos a área de Product Design é compreender seu significado, como ela se manifesta na criação de produtos digitais, como os profissionais da área a percebem e, principalmente, sua importância para a construção de soluções funcionais e desejáveis.
contents:
  - type: ARTICLE
    title: "Product Designer: o que faz a pessoa de Design de Produto?"
    link: https://pm3.com.br/blog/product-designer-o-que-faz-a-pessoa-de-design-de-produto/
  - type: ARTICLE
    title: "Introdução ao Product Design"
    link: https://brasil.uxdesign.cc/introdu%C3%A7%C3%A3o-ao-product-design-6b78e691f7bf
alura-contents:
  - type: COURSE
    title: "Product Design: o papel do designer de produtos"
    link: https://cursos.alura.com.br/course/product-design-papel-designer-produtos
  - type: COURSE
    title: "Product Design: realizando o processo de Product Discovery"
    link: https://cursos.alura.com.br/course/product-design-processo-product-discovery
  - type: COURSE
    title: "Design emocional: tornando um produto amável"
    link: https://cursos.alura.com.br/course/design-emocional-tornando-produto-amavel
  - type: COURSE
    title: "User Interface: conceitos de UI para Product Designers"
    link: https://cursos.alura.com.br/course/user-interface-conceitos-ui-product-designer
  - type: COURSE
    title: "Product Design: métricas e ciclo de vida do produto"
    link: https://cursos.alura.com.br/course/product-design-metricas-ciclo-vida-produto