name: Web Application - Vulnerabilidades
logo: 
short-description:
key-objectives:
  - As vulnerabilidades de aplicativos da Web envolvem uma falha ou fraqueza do sistema em um aplicativo baseado na Web. Eles existem há anos, em grande parte devido à não validação ou limpeza de entradas de formulário, servidores web mal configurados e falhas de design de aplicativos, e podem ser explorados para comprometer a segurança do aplicativo. Essas vulnerabilidades não são iguais a outros tipos comuns de vulnerabilidades, como rede ou ativo. Eles surgem porque os aplicativos da Web precisam interagir com vários usuários em várias redes, e esse nível de acessibilidade é facilmente aproveitado pelos hackers.
contents:
  - type: SITE
    title: "OWASP Top Ten"
    link: https://owasp.org/www-project-top-ten/
  - type: ARTICLE
    title: "Web Application Security Basics 101"
    link: https://medium.com/nerd-for-tech/devsecops-basics-where-to-start-aa7babee4ac4
  - type: ARTICLE
    title: "Web Application Security"
    link: https://medium.com/swlh/web-application-security-from-vulnerabilities-to-monitoring-7a3c2dfbfa23
  - type: ARTICLE
    title: "DVWA"
    link: https://medium.com/@rafaelrenovaci/instala%C3%A7%C3%A3o-dvwa-f70705af9d3e
  - type: ARTICLE
    title: "SQL Injection"
    link: https://medium.com/@rafaelrenovaci/dvwa-solution-sql-injection-3be3709caea4
  - type: ARTICLE
    title: "File Inclusion"
    link: https://medium.com/@rafaelrenovaci/dvwa-solution-file-inclusion-2a7f1504242b
  - type: ARTICLE
    title: "Brute Force"
    link: https://medium.com/@rafaelrenovaci/dvwa-solution-brute-force-ee44c29a25e0
  - type: YOUTUBE
    title: "OWASP 2021 Top 10 Web Application Vulnerabilities"
    link: https://www.youtube.com/watch?v=NATCMnghei0
  - type: COURSE
    title: "Cyber Security Fundamentals & Skills"
    link: https://www.fiap.com.br/shift/curso/tecnologia/cyber-security-fundamentals-e-skills-online/
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/