name: Web Application - Segurança
logo: 
short-description:
key-objectives:
  - A segurança de aplicativos da Web (também conhecida como Web AppSec) é a ideia de criar sites para funcionar conforme o esperado, mesmo quando estão sob ataque. O conceito envolve uma coleção de controles de segurança projetados em um aplicativo da Web para proteger seus ativos de agentes potencialmente maliciosos.
contents:
  - type: ARTICLE
    title: "How to Secure Web Apps — A Web App Security Checklist"
    link: https://medium.com/quick-code/how-to-secure-web-apps-a-web-app-security-checklist-bb27cf049d1d
  - type: ARTICLE
    title: "Web Application Security Basics"
    link: https://mtrdesign.medium.com/web-application-security-basics-9b7553f51e8a
  - type: ARTICLE
    title: "Web Application Security"
    link: https://pub.towardsai.net/web-application-security-top-11-best-practices-for-2020-c3a485e40de8
  - type: ARTICLE
    title: "Web Application Security Best Practices "
    link: https://javascript.plainenglish.io/web-application-security-best-practices-881e3cfde2a1
  - type: YOUTUBE
    title: "Web Application Security - Best Practices"
    link: https://www.youtube.com/watch?v=RedZvpyRd38
  - type: YOUTUBE
    title: "OWASP E O NOVO TOP 10 WEB APPLICATION SECURITY RISKS"
    link: https://www.youtube.com/watch?v=3EdFeJ0_mB0
  - type: YOUTUBE
    title: "7 Security Risks"
    link: https://www.youtube.com/watch?v=4YOpILi9Oxs
  - type: YOUTUBE
    title: "SAST / DAST"
    link: https://www.youtube.com/watch?v=5cOkNbH_jPU
  - type: COURSE
    title: "Cyber Security Fundamentals & Skills"
    link: https://www.fiap.com.br/shift/curso/tecnologia/cyber-security-fundamentals-e-skills-online/
  - type: COURSE
    title: "CSO infosec + Cyber Defense"
    link: https://www.fiap.com.br/shift/imersao/tecnologia/cso-infosec-cyber-defense/