name: Product Design
tags:
  - design
expertise:
  - name: UX Design
    cards:
      - first-contact-with-ux:
        priority: 10
      - starting-ux-strategy:
        priority: 9
      - ux-interaction-strategy-and-design:
        priority: 9
      - design-thinking:
        priority: 10
  - name: UI Design
    cards:
      - user-interface:
        priority: 10
      - visual-design-principles:
        priority: 9
      - figma:
        priority: 10
      - design-system:
        priority: 9
  - name: UX Research
    cards:
      - starting-ux-research:
        priority: 10
      - diving-in-ux-research:
        priority: 9
      - deep-dive-ux-research:
        priority: 9
collaboration:
  - name: Front-end
    cards:
      - html-fundamentals:
        priority: 10
      - css-fundamentals:
        priority: 10
      - javascript-fundamentals:
        priority: 7
  - name: Gestão e negócios
    cards:
      - product-management-fundamentals:
        priority: 10
      - roadmap:
        priority: 9
      - Strategic-Management-and-Decision-Making:
        priority: 9
      - agile-culture:
        priority: 9
video: 