name: Produção de Vídeo
tags:
  - Produção de Vídeo
expertise:
  - name: Produção de Vídeo
    cards:
      - essential-video-production-concepts:
        priority: 10
      - video-editing-fundamentals:
        priority: 10
      - creating-an-institutional-video:
        priority: 10
  - name: Produção de Vídeo Mid
    cards:
      - video-effects:
        priority: 9
      - sound-effects-and-music:
        priority: 9
      - videos-for-the-web:
        priority: 9
  - name: Produção de Vídeo in depth
    cards:
      - streaming-video-recording:
        priority: 8
      - obs-studio:
        priority: 8
      - streamlabs:
        priority: 8
collaboration:
  - name: Design para mídias sociais
    cards:
      - motion-design:
        priority: 10
      - social-media:
        priority: 9
      - copywriting:
        priority: 9
  - name: Marketing de conteúdo 
    cards:
      - digital-product-strategies-n-techniques:
        priority: 9
      - value-proposition:
        priority: 9
      - viral-marketing:
        priority: 9
      - roadmap:
        priority: 9