name: Product Design
tags:
  - design
expertise:
  - name: Fundamentos
    cards:
      - product-design:
        priority: 10
      - first-contact-with-ux:
        priority: 10
      - pd-user-interface:
        priority: 10
      - figma:
        priority: 9
  - name: Aprofundamento
    cards:
      - starting-ux-research:
        priority: 10
      - diving-in-ux-research:
        priority: 10
      - deep-dive-ux-research:
        priority: 10
      - data-driven-coleta-analise:
        priority: 9
      - data-driven-interpretando:
        priority: 9
      - acessibilidade-ux:
        priority: 10
  - name: Especialização
    cards:
      - ux-lead:
        priority: 10
      - design-system:
        priority: 9
collaboration:
  - name: Front-end
    cards:
      - html-fundamentals:
        priority: 10
      - css-fundamentals:
        priority: 10
      - javascript-fundamentals:
        priority: 7
  - name: Gestão e negócios
    cards:
      - product-management-fundamentals:
        priority: 10
      - product-management:
        priority: 10
      - roadmap:
        priority: 9
      - Strategic-Management-and-Decision-Making:
        priority: 9
      - agile-culture:
        priority: 9
video: 