name: CD - Continuous Delivery

on:
  push:
    branches: [ main ]

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'v20.14.0'
    - name: "Start: Deploy Static"
      run: |
        echo "===="
        echo $VERCEL_PROJECT_ID
        echo $VERCEL_TOKEN
        echo "===="
        yarn install && yarn build:static
        npx vercel ./out --yes --token=$VERCEL_TOKEN --prod
        echo "deployed with success!"
