name: Authentication and password security
logo: 
short-description:
key-objectives:
  - A strong password makes all the difference when it comes to data protection. After all, it is constructed in a way that makes it very difficult for it to be cracked by a hacker or mass attack. A password, you know, is a mechanism that allows a person access to a particular service.
contents:
  - type: SITE
    title: "How Secure is Your Password?"
    link: https://www.passwordmonster.com/
  - type: ARTICLE
    title: "Password 101 — How to create a more secure password"
    link: https://medium.com/belong-blog/password-101-how-to-create-a-secure-password-8adfbe888d79
  - type: ARTICLE
    title: "Password Security: THM Writeup"
    link: https://medium.com/bug-bounty-hunting/password-security-thm-writeup-cc9088207af3
  - type: ARTICLE
    title: "What Is a Secure Password?"
    link: https://medium.com/geekculture/what-is-a-secure-password-97263aeedea9
  - type: YOUTUBE
    title: "Bit Oxygen: Authentication in Computer Security"
    link: https://www.youtube.com/watch?v=7oTkgG1v-rU
  - type: YOUTUBE
    title: "Linus Tech Tips: Password Security Best Practices"
    link: https://www.youtube.com/watch?v=t8SQo3R7qeU
