name: Container Security
logo: 
short-description:
key-objectives:
  - Container security is the process of combining security policies to ensure that the integrity of the container is protected. Container security is important because the container image contains all the components that will eventually run your application. If there are vulnerabilities lurking in the container image, the risk and potential severity of security problems during production increases.
contents:
  - type: ARTICLE
    title: "Container Security Solutions"
    link: https://medium.com/xenonstack-security/container-security-solutions-framework-mechanism-and-strategy-24de3891a12b
  - type: ARTICLE
    title: "Container Security Threats"
    link: https://medium.com/oreillymedia/container-security-threats-38649261fb4f
  - type: ARTICLE
    title: "Top 20 Docker Security Tips"
    link: https://towardsdatascience.com/top-20-docker-security-tips-81c41dd06f57
  - type: ARTICLE
    title: "Container Security"
    link: https://blog.pentesteracademy.com/learning-path-container-security-9a9c47760250
  - type: YOUTUBE
    title: "IBM Technology: Container Security Explained"
    link: https://www.youtube.com/watch?v=b_euX_M82uI
  - type: YOUTUBE
    title: "The Linux Foundation: Container Security 101"
    link: https://www.youtube.com/watch?v=PDDiOl7ckzQ
  - type: YOUTUBE
    title: "HackerSploit: Docker Security Essentials"
    link: https://www.youtube.com/watch?v=KINjI1tlo2w
  - type: YOUTUBE
    title: "HackerSploit: Auditing Docker Security"
    link: https://www.youtube.com/watch?v=mQkVB6KMHCg