name: Endpoint security
logo: 
short-description:
key-objectives:
  - Endpoint security, or endpoint protection, is the cybersecurity approach to defending endpoints such as desktops, laptops, and mobile devices against malicious activity.
contents:
  - type: ARTICLE
    title: "Endpoint Security: I"
    link: https://medium.com/starting-up-security/endpoint-security-intuition-around-the-mudge-disclosures-dfbe014790f2
  - type: ARTICLE
    title: "Introduction to FireEye Endpoint Security"
    link: https://medium.com/@knoldus/introduction-to-fireeye-endpoint-security-3534c9bf60fe
  - type: ARTICLE
    title: "EPP vs EDR vs XDR: Endpoint Security Comparison"
    link: https://altexsoft.medium.com/epp-vs-edr-vs-xdr-endpoint-security-comparison-57409987f65e
  - type: ARTICLE
    title: "Endpoint Security -Antivirus, EPP & EDR"
    link: https://anandadip.medium.com/endpoint-security-antivirus-epp-edr-99496597b892
  - type: ARTICLE
    title: "What is Endpoint Detection and Response (EDR)"
    link: https://www.crowdstrike.com/cybersecurity-101/endpoint-security/endpoint-detection-and-response-edr/
  - type: ARTICLE
    title: "EDR vs. NGAV"
    link: https://www.crowdstrike.com/cybersecurity-101/endpoint-security/edr-vs-ngav/
  - type: ARTICLE
    title: "Introduction to Advanced Endpoint Protection (AEP)"
    link: https://www.crowdstrike.com/cybersecurity-101/endpoint-security/advanced-endpoint-protection-aep/
  - type: ARTICLE
    title: "Endpoint Security"
    link: https://www.crowdstrike.com/cybersecurity-101/endpoint-security/
  - type: YOUTUBE
    title: "Heimdal: Endpoint Security - Definition, Benefits, and Key Components"
    link: https://www.youtube.com/watch?v=2CVP9-Qslcw&ab_channel=Heimdal%C2%AE