name: Physical security
logo: 
short-description:
key-objectives:
  - Physical security is the protection of people, property, and physical assets from actions and events that could cause harm or loss. Although often overlooked in favor of cyber security, physical security is equally important.
contents:
  - type: ARTICLE
    title: "What Is Physical Security"
    link: https://www.sine.co/blog/what-is-physical-security-understanding-workplace-safety/
  - type: ARTICLE
    title: "Cyber Security and Physical Security"
    link: https://rchen8.medium.com/cyber-security-and-physical-security-are-very-different-22e31a933907
  - type: ARTICLE
    title: "What is a Physical Security Architect?"
    link: https://jay-pang.medium.com/what-is-a-physical-security-architect-2e8bd8b4b130
  - type: YOUTUBE
    title: "Tom Olzak: Physical Security Part 1 - Intro and Site Barriers"
    link: https://www.youtube.com/watch?v=j9MQMVn3FV4
  - type: YOUTUBE
    title: "Tom Olzak: Physical Security Part 2 - Walls, Doors, and Locks"
    link: https://www.youtube.com/watch?v=EAeVUDMDSn4
  - type: YOUTUBE
    title: "Tom Olzak: Physical Security Part 3 - Lights, Sensors, and Alarms"
    link: https://www.youtube.com/watch?v=tyFkj5UrPJQ
  - type: YOUTUBE
    title: "Tom Olzak: Physical Security Part 4 - Environmental Controls"
    link: https://www.youtube.com/watch?v=o_ENagQ60nY