name: PowerShell scripting for security
logo: 
short-description:
key-objectives:
  - A hidden script can be malicious and difficult to detect with visual inspection during the script approval process. Visually review PowerShell scripts and use inspection tools to help detect suspicious script issues. These tools cannot always determine the intent of the PowerShell author, so they may draw attention to a suspicious script.
contents:
  - type: ARTICLE
    title: "Using PowerShell for Password Security Checks"
    link: https://medium.com/@jeffreypinkstaff/using-powershell-for-password-security-checks-3e229c39303
  - type: ARTICLE
    title: "PowerShell — Testing your workstation security posture"
    link: https://medium.com/@smurf3r5/powershell-testing-your-workstation-security-posture-add06d4061eb
  - type: ARTICLE
    title: "Malicious PowerShell Usage Detection"
    link: https://0xneel.medium.com/malicious-powershell-usage-detection-f0ce9b6cca81
  - type: ARTICLE
    title: "Encrypt & Decrypt Data with PowerShell"
    link: https://medium.com/@sumindaniro/encrypt-decrypt-data-with-powershell-4a1316a0834b
  - type: ARTICLE
    title: "Run PowerShell without Powershell.exe"
    link: https://bank-security.medium.com/how-to-running-powershell-commands-without-powershell-exe-a6a19595f628
  - type: YOUTUBE
    title: "QuickStart: Using PowerShell for Cyber Security"
    link: https://www.youtube.com/watch?v=K9zVwijJ4nk
  - type: YOUTUBE
    title: "Michael Ferrie: Scripting for Security 1 - Introduction to PowerShell"
    link: https://www.youtube.com/watch?v=XQlVi_OJ2ZA
  - type: YOUTUBE
    title: "SecurityFWD: Beginner's Guide to Building AD Security Tools with PowerShell"
    link: https://www.youtube.com/watch?v=Kk7nJe1T-ik
