name: Software Application Security
logo: 
short-description:
key-objectives:
  - Application security describes the application-level security measures that aim to prevent data or code within the application from being stolen or hacked. It covers security considerations that occur during application development and design, but also involves systems and approaches to securing applications after they are deployed. 
contents:
  - type: ARTICLE
    title: "Application security vs. software security"
    link: https://medium.com/@SW_Integrity/application-security-vs-software-security-whats-the-difference-3d345413927c
  - type: ARTICLE
    title: "A Comprehensive Guide To Application Security"
    link: https://medium.com/edureka/application-security-tutorial-e6a0dda25f5c
  - type: ARTICLE
    title: "Application Security Best Practices"
    link: https://medium.com/@cloud_tips/application-security-best-practices-c63b79f29a99
  - type: ARTICLE
    title: "Importance of Software Security"
    link: https://medium.com/nerd-for-tech/importance-of-software-security-application-security-non-technical-hacking-encryption-and-365c93def04e
  - type: YOUTUBE
    title: "Application Security 101 - What you need to know in 8 minutes"
    link: https://www.youtube.com/watch?v=Dp019cWu1cg&t=1s&ab_channel=Snyk
  - type: YOUTUBE
    title: "edureka!: Application Security"
    link: https://www.youtube.com/watch?v=gfFKuiZ9Y7s
  - type: YOUTUBE
    title: "GOTO Conferences: Secure by Design – the Architect's Guide to Security Design Principles"
    link: https://www.youtube.com/watch?v=4qN3JBGd1g8
  - type: YOUTUBE
    title: "Cybr: Introduction to Application Security - Course"
    link: https://www.youtube.com/watch?v=3QOlo2pEpvc&ab_channel=Cybr

