name: Web application - Vulnerability
logo: 
short-description:
key-objectives:
  - Web application vulnerabilities involve a system flaw or weakness in a web-based application. They have existed for years, largely due to failure to validate or clean form entries, misconfigured web servers, and application design flaws, and can be exploited to compromise the security of the application. These vulnerabilities are not the same as other common types of vulnerabilities, such as network or asset. They arise because web applications need to interact with multiple users on multiple networks, and this level of accessibility is easily exploited by hackers.
contents:
  - type: SITE
    title: "OWASP Top Ten"
    link: https://owasp.org/www-project-top-ten/
  - type: ARTICLE
    title: "Web Application Security Basics 101"
    link: https://medium.com/nerd-for-tech/devsecops-basics-where-to-start-aa7babee4ac4
  - type: ARTICLE
    title: "Web Application Security: From Vulnerabilities to Monitoring"
    link: https://medium.com/swlh/web-application-security-from-vulnerabilities-to-monitoring-7a3c2dfbfa23
  - type: ARTICLE
    title: "How to Install DVWA Into Your Linux Distribution"
    link: https://medium.datadriveninvestor.com/setup-install-dvwa-into-your-linux-distribution-d76dc3b80357
  - type: ARTICLE
    title: "SQL Injection Attack in DVWA with Low Security Level"
    link: https://audreybetsy.medium.com/sql-injection-attack-in-dvwa-f6adc95f239b
  - type: ARTICLE
    title: "StackZero: Hack File Inclusion in DVWA: A Full Walkthrough"
    link: https://stackzero.net/hack-file-inclusion-in-dvwa-a-full-walkthrough/
  - type: ARTICLE
    title: "StackZero: How to Brute Force DVWA login with Python"
    link: https://stackzero.net/brute-force-dvwa-python/
  - type: YOUTUBE
    title: "Cloud Security Training & Consulting: OWASP 2021 Top 10 Web Application Vulnerabilities"
    link: https://www.youtube.com/watch?v=NATCMnghei0
  - type: YOUTUBE
    title: "CryptoCat: Damn Vulnerable Web Application (DVWA) (Playlist)"
    link: https://www.youtube.com/playlist?list=PLHUKi1UlEgOJLPSFZaFKMoexpM6qhOb4Q