name: Web application - Security
logo: 
short-description:
key-objectives:
  - Web application security (also known as Web AppSec) is the idea of designing websites to function as expected, even when under attack. The concept involves a collection of security controls designed into a web application to protect its assets from potentially malicious agents.
contents:
  - type: ARTICLE
    title: "How to Secure Web Apps — A Web App Security Checklist"
    link: https://medium.com/quick-code/how-to-secure-web-apps-a-web-app-security-checklist-bb27cf049d1d
  - type: ARTICLE
    title: "Web Application Security Basics"
    link: https://mtrdesign.medium.com/web-application-security-basics-9b7553f51e8a
  - type: ARTICLE
    title: "Web Application Security"
    link: https://pub.towardsai.net/web-application-security-top-11-best-practices-for-2020-c3a485e40de8
  - type: ARTICLE
    title: "Web Application Security Best Practices "
    link: https://javascript.plainenglish.io/web-application-security-best-practices-881e3cfde2a1
  - type: YOUTUBE
    title: "House Of Secure Network: Web Application Security - Best Practices"
    link: https://www.youtube.com/watch?v=RedZvpyRd38
  - type: YOUTUBE
    title: "freeCodeCamp.org: Web application security - 10 things developers need to know"
    link: https://www.youtube.com/watch?v=3EdFeJ0_mB0
  - type: YOUTUBE
    title: "Fireship: 7 Security Risks"
    link: https://www.youtube.com/watch?v=4YOpILi9Oxs
  - type: YOUTUBE
    title: "Crashtest Security: SAST, DAST, IAST, RASP Explained"
    link: https://www.youtube.com/watch?v=5cOkNbH_jPU